### ISSUE TITLE
Drag events on zoomed image propagating to scroll on mobile

### ISSUE THREAD

**Issue by mhalle** [laurenashpole/react-inner-image-zoom#43] opened 2021-03-15 13:15 UTC
On mobile platforms (Chrome on Android and jOS, possibly others), dragging the zoomed image causes the underlying page to scroll. 

This bug can be seen on the demos on the demo site, including the fullscreen mobile demo.

I did a quick look at the source, but couldn't find where the touch event is propagating when it shouldn't.

Thanks for maintaining this component!

**Comment by laurenashpole** [comment] 2021-03-23 21:08
Hey @mhalle, 

Could you let me know what versions of Chrome and iOS you're seeing this on? I'm having trouble reproducing but I'm also terrible at updating apps and software.

**Comment by StephanJ98** [comment] 2021-05-01 10:18
Hey @laurenashpole,

I tried to reproduce the issue and found it in Android Chrome 90.0.4430.91 and versions before and all others based on these versions of Chrome.

**Comment by pm0u** [comment] 2021-07-27 14:48
I am noticing this as well on your demo "Fullscreen on Mobile" android 12, chrome 92.0.4515.115

**Comment by pm0u** [comment] 2021-07-29 18:29
I will add that I do not experience this issue in my implementation.. unsure what the difference is but I think it may just be that it is within a modal that is already locking the body scroll.

**Comment by laurenashpole** [comment] 2021-07-30 16:03
I wonder if this is related to https://github.com/laurenashpole/react-inner-image-zoom/issues/63, it looks like something may have cropped up around how browsers handle canceling touchmove events. Thanks @StephanJ98 and @pm0u for the additional info! It's super helpful.

**Comment by pm0u** [comment] 2021-07-30 20:20
I'll just add as well -- I am not seeing those console errors from #63 in my implementation. I am using the package `body-scroll-lock` to lock the body manually when the modal containing the image zoom image is open.

**Comment by laurenashpole** [comment] 2021-08-05 06:12
Well, I never did figure out why this was happening in some cases but not others (I could reproduce it on the gh-pages branch but not the master branch). _However_, while I was researching I noticed that the CSS `touch-action` property has better support than it did before and is a more performant way to prevent scrolling so I swapped that out in v2.0.3. That should fix the problem so I'm going to close this issue, feel free to re-open if you notice it again.

**Closed by laurenashpole** 2021-08-05 06:12 UTC
